### PR TITLE
fix: ignore variable mode value if it is a variable alias

### PR DESCRIPTION
**Pull request by torleifhalseth**
If the variable mode value is referencing a remote variable we should ignore it when generating the post variables payload.

### CODE REVIEW

**Comment by torleifhalseth** [comment]
Appreciate the example project you put together @james04321! 🎖️

In our variables setup we have two libraries (Primitives, Themes). Variables in the themes library reference variables in the primitives library.  

When I tested this in the context of our project the script `sync-tokens-to-figma` added the referenced primitive color values to the payload (variableModeValues) and then generated these variables in the themes.  I modified the `generatePostVariablesPayload` to check if the value is of type `VARIABLE_ALIAS`. 

Please correct me if the code suggested for ignoring these variables does not make sense or if we should fix this some other way. 

Cheers 🍻

**Comment by james04321** [comment]
Thanks for bringing this up @torleifhalseth! I think we forgot to test for aliases to remote variables.

I'll look at this later this week when I get the chance. Does this pass the existing tests?

**Comment by torleifhalseth** [comment]
Yes, existing tests are passing ✅

**Comment by torleifhalseth** [comment]
I revisited this with fresh eyes today and found that the tests included the remote variable aliases in the `variableModeValues`.  I updated the tests to exclude these from the resulting output so that they are not included in the variables POST payload. I updated the `isVariableAlias` to check the new variable value and not the existing variable value because the existing variable value would always return null. 

Does this make sense @james04321 ?

**Comment by torleifhalseth** [comment]
I believe I am looking at this from the wrong place just now. I will try to refactor this to check if the variable is an alias before adding it to the `postVariablesPayload.variables` part.

**Comment by james04321** [comment]
> How would we know if a token in file should create a new Figma Variable or if it is an external reference?

My immediate intuition (that I haven't thought through fully yet) is that we should include remote variable aliases in `variableModeValues` whenever possible. That is, if a remote variable is already materialized in the current file (is referenced by another local variable), then we should allow setting aliases to this variable in the script.

However, we are limited by the API in that we can't bring in remote variables that don't already live in the current file.

When I have time later (probably next week), I want to think through how the export/import scripts work with remote variables to make sure we're handling them consistently.

In the meantime, feel free to make whatever changes you need in your own fork if you're blocked by this. We might not end up using the changes in this PR depending on where we land, so don't feel like you have to polish everything right now.

**Comment by torleifhalseth** [comment]
Sounds like a good idea @james04321 . I will leave this for now and wait for your feedback/solution for working with remote variables.

**Comment by torleifhalseth** [comment]
Great work @james04321 🎖️ The solution works great for us. Thank you for taking the time to follow up and fixing this. 

For now, we are duplicating this code in our project, but it would be great if this was packaged at some point. Is that something you guys would consider @james04321? The same way you did with the `@figma/rest-api-spec`. This was a great improvement. Makes it much easier for developers to start working with the API 👍

**Comment by james04321** [comment]
> The same way you did with the `@figma/rest-api-spec`. This was a great improvement. Makes it much easier for developers to start working with the API 👍

😍 Glad you are finding the spec useful!

> For now, we are duplicating this code in our project, but it would be great if this was packaged at some point.

We don't have plans to do this primarily because there are a bunch of opinionated design decisions in the code such as the format of the tokens json, intentionally conservative behavior (not removing variables in the Figma file that have been removed in the tokens file), etc... and we want organizations using this code to be intentional about how they're setting up their Figma-GitHub sync to avoid messing up their Figma files.

**Comment by torleifhalseth** [comment]
Ok. I understand. I guess the opinionated design decisions could be configurable,  but then the code complexity increases 🤷‍♂️  

This example is a great starting point for developers, and I agree that we should be intentional about how we are setting up the sync. I also think the majority of designers and developers appreciate opinionated decisions when they are described and well thought over 🚀

**Pull request closed without merging**
